title: 我的个人博客
email: your-email@example.com
description: >-
  我的个人技术博客，分享编程、技术和生活经验。
baseurl: "" # 如果是项目站点，例如 "/blog"
url: "" # 你的GitHub Pages URL，如 "https://username.github.io"
twitter_username: 
github_username: 

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 分页设置
paginate: 5
paginate_path: "/blog/page:num/"

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 