name: Jekyll站点CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 设置Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: 安装依赖
        run: |
          gem install bundler
          bundle install

      - name: 构建站点
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: 上传构建文件
        uses: actions/upload-pages-artifact@v1
        with:
          path: "_site/"

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 